### ISSUE TITLE
FEATURE REQUEST: Ulanzi Pixel Clock Support

### ISSUE THREAD

**Issue by aptonline** [pixelit-project/PixelIt#259]
Flagging this here as a general feature request after starting a post in discussions and also within Discord.

https://github.com/pixelit-project/PixelIt/discussions/258

**Comment by aptonline** [comment]
While we wait for official support, I’ve forked the project so that fixes can be applied specific to Ulanzi, namely removal of the constant tone the Ulanzi emits when powered on using the stock PixelIt firmware.

Other fixes are also being applied but likely no major features will be implemented.

https://github.com/aptonline/PixelIt_Ulanzi

**Comment by jekader** [comment]
Using the PixelIt_Ulanzi fork for about a month already with no issues and I expect more people to try flashing their devices with alternative firmware. It would be great to have the changes merged upstream and get binary downloads for users who are not comfortable with installing Platformio and building firmware by themselves.

**Comment by aptonline** [comment]
I think that might be the next logical step, is the PixelIt project still being actively developed?

**Comment by foorschtbar** [comment]
> I think that might be the next logical step, is the PixelIt project still being actively developed?

Yes, but its a community project and without input and developers, no new features will come. All must-haves are implemented. Feel free to add new ideas or PRs.

**Comment by jekader** [comment]
Had a quick look at the diff from the Ulanzi fork. It seems to overwrite existing platforms instead of adding a new one:
https://github.com/pixelit-project/PixelIt/compare/main...aptonline:PixelIt_Ulanzi:main

In order to merge it in, the customizations need to be defined as a separate platform such as:

```
[env:ulanzi_tc001]
 platform = espressif32
 board = esp32dev
```
 
Pin definitions and other tweaks related to this device like the battery monitor need to be parametrized to keep existing functionality intact. @aptonline would you be interested in preparing these changes for merging in? Otherwise I can try doing this when I have some spare time.
